### ISSUE TITLE
migration not supporting mongo replicas

### ISSUE THREAD

**Issue by pandey-vikesh** [commercehub-oss/dropwizard-mongeez#2]
so we have moved from single mongo host to mongo replication supporting upto three hosts. so the earlier config was something like : 
    uri: mongodb://username:password!host1:27017/testdb?replicaSet=rs0&maxPoolSize=50&maxIdleTimeMS=300000
  dbName: testdb

after replication, we changed it to: 
  uri: mongodb://username:password!host1:27017,host2:27017,host3:27017/testdb?replicaSet=rs0&maxPoolSize=50&maxIdleTimeMS=300000
  dbName: testdb

and the mongo migration is failing. Does it support multiple hosts? Any quick help will be deeply appreciated.

Thanks,
Vikesh
skype: vikesh_nagarro4010

**Comment by mhurne** [comment]
Vikesh, in what way does the migration fail?

**Comment by pandey-vikesh** [comment]
INFO  [2015-12-08 06:43:58,049] org.mongeez.reader.FilesetXMLReader: Num of changefiles 1
Exception in thread "main" com.mongodb.CommandFailureException: { "serverUsed" : "testIp:27017" , "ok" : 0.0 , "errmsg" : "auth failed" , "code" : 18}
        at com.mongodb.CommandResult.getException(CommandResult.java:76)
        at com.mongodb.CommandResult.throwOnError(CommandResult.java:131)
        at com.mongodb.DBPort$NativeAuthenticator.authenticate(DBPort.java:652)
        at com.mongodb.DBPort.authenticate(DBPort.java:364)
        at com.mongodb.DBPort.checkAuth(DBPort.java:375)
        at com.mongodb.DBTCPConnector.doOperation(DBTCPConnector.java:209)
        at com.mongodb.DBCollectionImpl.sendWriteCommandMessage(DBCollectionImpl.java:475)
        at com.mongodb.DBCollectionImpl.writeWithCommandProtocol(DBCollectionImpl.java:425)
        at com.mongodb.DBCollectionImpl.updateWithCommandProtocol(DBCollectionImpl.java:415)
        at com.mongodb.DBCollectionImpl.update(DBCollectionImpl.java:267)
        at com.mongodb.DBCollection.update(DBCollection.java:191)
        at org.mongeez.dao.MongeezDao.addTypeToUntypedRecords(MongeezDao.java:56)
        at org.mongeez.dao.MongeezDao.configure(MongeezDao.java:47)
        at org.mongeez.dao.MongeezDao.<init>(MongeezDao.java:43)
        at org.mongeez.ChangeSetExecutor.<init>(ChangeSetExecutor.java:36)
        at org.mongeez.Mongeez.process(Mongeez.java:40)


We are able to connect to this db from the REST service. but while running the migration it says its no able to connect. Though it looks like a config miss from our end. But i tried the following:
- connect the mongo shell using same creds- worked fine
- service is able to connect to db fine with same creds

Thanks

**Comment by pandey-vikesh** [comment]
one more finding.. so we are using mongo 2.6 and mongo java driver version 2.2, which is bit outdated. the mongeez lib used in your project uses mongo 3.0 and mongo java driver version is also 3.x. so when you create users with old mongo 2.6 it created users wth Mongo CR credentials and system version 3. but new mongo versions create and authenticate users with SHA-1 creds with system version 5. It is diferent way of storing and fetching credentials. 

This might be creating the issue. As all my users are created on 2.6, and i am trying to use a new java driver(provided in your project) to connect to DB. even the auth code 18 is pointing to this issue only.

But could you please once validate your project so that we can be rest assured that the issue is at our end. Thanks

**Comment by mhurne** [comment]
`mongo-java-driver` is a transitive dependency for `dropwizard-mongeez` which comes from its direct dependency on `dropwizard-mongo`. Currently, `dropwizard-mongeez` depends on `dropwizard-mongo 2.0.0` which depends on `mongo-java-driver 2.12.3`. According to https://docs.mongodb.org/ecosystem/drivers/driver-compatibility-reference/#reference-compatibility-mongodb-java `mongo-java-driver 2.12.x` is compatible with MongoDB 2.4.x and 2.6.x.

What led you to conclude that `dropwizard-mongeez` uses MongoDB 3.0 and `mongo-java-driver 3.x`? Perhaps there are other dependencies in your project that bring in `mongo-java-driver` as well, but a different version, and your build tool is resolving the version conflict by bringing in `mongo-java-driver 3.x`?

**Comment by mhurne** [comment]
By the way, according to the aforementioned Driver Compatibility document, `mongo-java-driver 3.x` is also compatible with MongoDB 2.4.x and 2.6.x (in addition to 3.0.x).

**Comment by pandey-vikesh** [comment]
We are not supplying mongo 3.x but it is mongeez 0.9.4 which supplies mongo 3.x and mongeez is supplied in dropwizard mongeez. And as i mentioned, the issue comes if you use some authentication mechanism to connect to mongodb. Though rest of the operations work fine. Please go through this link:
http://stackoverflow.com/questions/18216712/cannot-authenticate-into-mongo-auth-fails

**Comment by mhurne** [comment]
I have attached the [Gradle dependency report](https://github.com/commercehub-oss/dropwizard-mongeez/files/62528/deps.txt) for `dropwizard-mongeez`. In the report we can see all dependencies on `mongo-java-driver`, which versions each of our dependencies is asking for, and which version is selected by Gradle. `mongeez` asks for `2.11.1`, but the version selected is `2.12.3`, because that's the version `dropwizard-mongo` requests.

If you're ending up with `mongo-java-driver 3.x`, I'm afraid it must be coming from some other dependency of your project.

**Comment by pandey-vikesh** [comment]
aah there is a confusion. So if you look at the mongeez github code, it says that the code for upgrade to mongo 3.x has been written and merged to the repo. but the original contributors of mongeez have not published and released it. Thats really bad. looks like, either i have to fork their repo and publish in our organization's internal repo and use it or downgrade my mongo drivers.

**Comment by mhurne** [comment]
I see - in that case, I'll go ahead and close this issue. Thanks!
