### ISSUE TITLE
new release compatible with mongeez 0.9.5?

### ISSUE THREAD

**Issue by pandey-vikesh** [commercehub-oss/dropwizard-mongeez#3]
Recently, mongeez published its latest release 0.9.5 and 0.9.6. Could you please let me know if dropwizard-mongeez current release is compatible with latest mongeez libraries? i have a forked copy of this project and i upgraded it manually. It compiles fine but it breaks on running the migration. 
Please refer to https://github.com/mongeez/mongeez/issues/56 

Appreciate any inputs.

Thanks,
Vikesh

**Comment by mhurne** [comment]
At first glance, I'm not sure whether dropwizard-mongeez is compatible with mongeez 0.9.5 or 0.9.6. There aren't any release notes on the mongeez project page, so we'll just have to try it to find out. I'll try to do that soon, but in the meantime you should be able to force which version of mongeez your application uses, overriding the version dropwizard-mongeez requests.

**Comment by epishkin** [comment]
@mhurne, @pandey-vikesh 
* I've created [CHANGES.md] file with all the changes in mongeez
* and added same info to [all releases] on github

[CHANGES.md]: https://github.com/mongeez/mongeez/blob/master/CHANGES.md
[all releases]: https://github.com/mongeez/mongeez/releases

**Comment by pandey-vikesh** [comment]
yes, That is what i did. I have forced dropwizard-mongeez to use 0.9.5 of mongeez. And it breaks with the error i mentioned in https://github.com/mongeez/mongeez/issues/56 . i had to disable authentication to make it work. You may try it with keeping authentication on and try running some test migrations to see if you are also getting same kind of error. Though i think it might be a mongeez issue but just to be sure dropwizard-mongeez is behaving fine.

**Comment by mhurne** [comment]
Thanks for the pointer to the mongeez changelog, @epishkin !

**Comment by mhurne** [comment]
Upgrading to mongeez 0.9.6 results in a mongo-java-driver upgrade from 2.12.3 to 3.0.1. Per the release notes for mongo-java-driver 3.0.0, the 3.x mongo-java-driver release series is not binary or source compatible with the 2.x release series. It doesn't look like any of the code in dropwizard-mongeez itself breaks with the upgrade, but it relies heavily on dropwizard-mongo, so I'll have to take a look at that too. Stay tuned...

**Comment by mhurne** [comment]
Based on my testing, dropwizard-mongeez, dropwizard-mongo and jackson-datatype-mongo should all be compatible with mongo-java-driver 3.0.1, despite the fact that the 3.x mongo-java-driver release series is not compatible with the 2.x release series.
